name: Build and test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using macOS and the available iPhone simulator
    runs-on: macos-14
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
    # target macOS 12.4 isn't supported in default Xcode for macOS 12
    # macos-14:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

    #strategy:
    #  matrix:
    #    run-config:
    #      - { scheme: 'SPISearch', destination: 'platform=macOS' }
    #      - { scheme: 'SPISearch', destination: 'platform=iOS Simulator,OS=15.5,name=iPhone 8' }

          #  env:
          #DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Show the version of Xcode
        run: xcodebuild -version

      - name: Show current build settings
        run: xcodebuild -showBuildSettings

      - name: Show available build SDK
        run: xcodebuild -showsdks

      - name: Show available build destinations
        run: xcodebuild -showdestinations -scheme 'SPISearch'

      # iOS 15.2, macOS 12.1 on macOS-latest (11)
      # iOS 15.5, macOS 12.3 on macOS-12 w/ Xcode 13.4.1

      - name: iOS build
        # macOS 12: run: xcodebuild clean build -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 8' -sdk iphonesimulator16.2 -showBuildTimingSummary
        # macOS13: OS=16.4, iphonesimulator16.4 sdk (iPhone 8)
        # macOS14: OS=17.0, iphonesimulator17.0 sdk (iPhone 14)
        run: xcodebuild clean build -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=17.0.1,name=iPhone 14' -sdk iphonesimulator17.0.1 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

          #- name: iOS test
          #  run: xcodebuild build-for-testing test -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 14' -sdk iphonesimulator17.0 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

      - name: macOS build for SPISearch
        # macOS-12 stopped at SDK version macosx13.1
        # macOS-13 - 13.3
        # macOS 14 - 14.0
        run: xcodebuild clean build -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx14.0 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

      #- name: macOS build for testing SPISearch
      #  run: xcodebuild build-for-testing -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx14.0 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

      #- name: macOS test for SPISearch
      #  run: xcodebuild test -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx12.3 -showBuildTimingSummary

      - name: macOS build for ReportSearch
        run: xcodebuild clean build -scheme 'ReportSearch' -destination 'platform=macOS' -sdk macosx14.0 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

      - name: macOS build for CaptureSearches
        run: xcodebuild clean build -scheme 'CaptureSearches' -destination 'platform=macOS' -sdk macosx14.0 -showBuildTimingSummary -skipPackagePluginValidation -skipMacroValidation

# w/ Xcode 14 beta 3:
# Local: xcodebuild clean test -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 8' -sdk iphonesimulator16.0
# w/ Xcode 15.4 beta 2:
# Local:
# xcodebuild clean test -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15' -sdk iphonesimulator17.4

#export DEVELOPER_DIR=/Applications/Xcode.app
#xcodebuild clean build -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 8' -sdk iphonesimulator15.5
#xcodebuild clean build -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx13.3
