name: Build and test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
    # target macOS 12.4 isn't supported in default Xcode for macOS 12

    #strategy:
    #  matrix:
    #    run-config:
    #      - { scheme: 'SPISearch', destination: 'platform=macOS' }
    #      - { scheme: 'SPISearch', destination: 'platform=iOS Simulator,OS=15.5,name=iPhone 8' }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Select Xcode 13.4.1
      #  run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
      #env:
      #  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer

      #- name: Show what's in Applications
      #  run: ls -al /Applications

      - name: Show the version of Xcode
        run: xcodebuild -version

      - name: Show current build settings
        run: xcodebuild -showBuildSettings

      - name: Show available build SDK
        run: xcodebuild -showsdks

      - name: Show available build destinations
        run: xcodebuild -showdestinations -scheme 'SPISearch'

      # iOS 15.2, macOS 12.1 on macOS-latest (11)
      # iOS 15.5, macOS 12.3 on macOS-12 w/ Xcode 13.4.1

      #- name: iOS xcodebuild basic invoke
      #  run: xcodebuild clean test -scheme 'SPISearch'

      - name: iOS build
        run: xcodebuild clean build -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 8' -sdk iphonesimulator16.2 -showBuildTimingSummary

      #- name: iOS test
      #  run: xcodebuild clean test -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 8' -sdk iphonesimulator15.5 -showBuildTimingSummary

      - name: macOS build for SPISearch
        run: xcodebuild clean build -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx13.1 -showBuildTimingSummary

      - name: macOS build for testing SPISearch
        run: xcodebuild build-for-testing -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx13.1 -showBuildTimingSummary

      #- name: macOS test for SPISearch
      #  run: xcodebuild test -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx12.3 -showBuildTimingSummary

      - name: macOS build for ReportSearch
        run: xcodebuild clean build -scheme 'ReportSearch' -destination 'platform=macOS' -sdk macosx13.1 -showBuildTimingSummary

# w/ Xcode 14 beta 3:
# Local: xcodebuild clean test -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=16.0,name=iPhone 8' -sdk iphonesimulator16.0

#export DEVELOPER_DIR=/Applications/Xcode.app
#xcodebuild clean build -scheme 'SPISearch' -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 8' -sdk iphonesimulator15.5
#xcodebuild clean build -scheme 'SPISearch' -destination 'platform=macOS' -sdk macosx13.3
